### ISSUE TITLE
UnrealCV server is not running

### ISSUE THREAD

**Issue by huxianer** [LilJing/pose-assisted-collaboration#1]
Hi,Thanks for your good job! Could you tell me how to deal this?

ERROR:init:205:Can not connect to ('127.0.0.1', 9005)
ERROR:init:206:Error [Errno 111] Connection refused
UnrealCV server is not running. Please try again

**Comment by Damax18** [comment]
@huxianer hi, i have the same problem, do you solve it? thanks

**Comment by GradiusTwinbee** [comment]
@Damax18 @huxianer Hi, I have the same problem too, do you solve it? thanks.
